//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Listings_Schmidt_Surieux.Ressources
{
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyAppRessources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyAppRessources()
        {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeBonAngle.Ressources.MyAppRessources", typeof(MyAppRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le bon angle.
        /// </summary>
        internal static string ApplicationName
        {
            get
            {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des annonces.
        /// </summary>
        internal static string ItemMenu1
        {
            get
            {
                return ResourceManager.GetString("ItemMenu1", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publier une annonce.
        /// </summary>
        internal static string ItemMenu2
        {
            get
            {
                return ResourceManager.GetString("ItemMenu2", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messagerie.
        /// </summary>
        internal static string ItemMenu3
        {
            get
            {
                return ResourceManager.GetString("ItemMenu3", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string LoginPage_BtnSubmit
        {
            get
            {
                return ResourceManager.GetString("LoginPage_BtnSubmit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner vos identifiants !.
        /// </summary>
        internal static string LoginPage_LblError_Uncomplete
        {
            get
            {
                return ResourceManager.GetString("LoginPage_LblError_Uncomplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de se connecter, veuillez ressayer..
        /// </summary>
        internal static string LoginPage_LblError_Unknown
        {
            get
            {
                return ResourceManager.GetString("LoginPage_LblError_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email :.
        /// </summary>
        internal static string LoginPage_LblLogin
        {
            get
            {
                return ResourceManager.GetString("LoginPage_LblLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe :.
        /// </summary>
        internal static string LoginPage_LblPwd
        {
            get
            {
                return ResourceManager.GetString("LoginPage_LblPwd", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publier une annonce.
        /// </summary>
        internal static string Title_AnnounceCreate
        {
            get
            {
                return ResourceManager.GetString("Title_AnnounceCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annonce {0}.
        /// </summary>
        internal static string Title_AnnounceDetailPage
        {
            get
            {
                return ResourceManager.GetString("Title_AnnounceDetailPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des annonces.
        /// </summary>
        internal static string Title_AnnouncesPage
        {
            get
            {
                return ResourceManager.GetString("Title_AnnouncesPage", resourceCulture);
            }
        }
    }
}
